config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    authenticated :user do
      root to: 'posts#index', as: :authenticated_root
      resources :places
    end
  
    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :admin do
    resources :users do
      resources :posts, only: [ :index, :show, :destroy ]
    end
    # resources :posts, only: [ :show ]
  end
  
  resources :places

  resources :posts do
  	resources :comments
    resources :inquiries
    patch :report, on: :member
  end

  resources :users, only: [:index, :show, :update] do
    resources :reviews
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :inquiries, dependent: :destroy

  validates :pet_name, presence: true
  validates :category, presence: true
  validates :breed, presence: true
  validates :price, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :reported, inclusion: { in: [true, false] }

  mount_uploader :thumbnail, ThumbnailUploader
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
    before_action :set_user
    before_action :set_post, only: [ :show, :destroy]
    def index
        @posts = @user.posts
    end

    def show
    end

    def destroy
        if @post.destroy
            redirect_to admin_user_posts_path, notice: 'Post was successfully destroyed.'
        else
            render :show
        end
    end

    private
        def set_user
            @user = User.find(params[:user_id])
        end

        def set_post
            @post = @user.posts.find(params[:id])
        end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_if_admin
  before_action :set_post, only: [:show, :edit, :update, :destroy, :report]

  def index
    @posts = Post.where(availability: "available").order('created_at DESC')
  end

  def show
    @inquiry = @post.inquiries.find_by(inquirer_name: current_user.email)
  end

  def new
    @post = current_user.posts.build
  end

  def create 
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to post_url(@post), notice: 'Post create!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      # Handle successful update
      redirect_to @post, notice: 'Post updated.'
    else
      # Handle unsuccessful update
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post deleted.'
  end

  # Report post
  def report
    @post.update(reported: true)
    redirect_to post_path(@post), notice: 'Post reported'
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end


  def post_params
    params.require(:post).permit(:phone, :owner, :pet_name, :category, :breed, :price, :description, :pick_up, :location, :thumbnail, :availability, :advertisement)
  end

  
    def check_if_admin
      if current_user.admin?
        redirect_to '/admin/users'
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/index.html.erb
<div class="container" style="gap: 1.5rem;">
    <div class="post-category-wrapper">
        <span>Reported</span>
        <div class="post-category">
            <% @posts.each do |post| %>
                <% if post.reported == true %> 
                    <div class="card" style="width: 15rem;">
                        <div  class="card-img-top" >
                            <%= image_tag post.thumbnail_url, class: "pet-thumbnail"%>
                        </div>
                        <div class="card-body">
                            <div class="card-index">
                                <p class="card-title d-flex justify-content-center text-success"> <%= post.advertisement %>: <%= post.pet_name.titleize  %></p>
                                <p class="card-text"><i class="fa-solid fa-paw"></i> <%= post.category.titleize %>, <%= post.breed.titleize %></p>
                                <p class="card-text"><i class="fa-solid fa-user"></i> <%= post.owner %></p>
                                <p class="card-text"><i class="fa-solid fa-location-dot"></i> <%= post.location %></p> 
                            </div>
                            <%= link_to "Details", admin_user_post_path(@user, post), class: "btn btn-secondary btn-sm" %>
                        </div>
                    </div>
                <% end %>
            <% end %>
        </div>
        <span>Safe</span>
        <div class="post-category">
            <% @posts.each do |post| %>
                <% if post.reported != true %> 
                    <div class="card" style="width: 15rem;">
                        <div  class="card-img-top" >
                            <%= image_tag post.thumbnail_url, class: "pet-thumbnail"%>
                        </div>
                        <div class="card-body">
                            <div class="card-index">
                                <p class="card-title d-flex justify-content-center text-success"> <%= post.advertisement %>: <%= post.pet_name.titleize  %></p>
                                <p class="card-text"><i class="fa-solid fa-paw"></i> <%= post.category.titleize %>, <%= post.breed.titleize %></p>
                                <p class="card-text"><i class="fa-solid fa-user"></i> <%= post.owner %></p>
                                <p class="card-text"><i class="fa-solid fa-location-dot"></i> <%= post.location %></p> 
                            </div>
                            <%= link_to "Details", admin_user_post_path(@user, post), class: "btn btn-secondary btn-sm" %>
                        </div>
                    </div>
                <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/admin/posts/show.html.erb
<div class="d-flex justify-content-center gap-2 mt-5" >
    <div class="card post-card" style="width: 30rem; max-height: 600px;">
        <div  class="card-img-top mb-2 mt-3" style="background-color: #86C8BC;">
                <%= image_tag @post.thumbnail_url, class: "pet-thumbnail"%>
        </div> 
        <div class="card-body">
            <div class="d-flex align-items-center gap-2">
                <p style="color: green;"><strong><%= @post.advertisement %></strong></p> <p><%= @post.pet_name.titleize  %></p>
            </div>
            <p class="card-text"><strong>Category:</strong> <%= @post.category.titleize %></p>
            <p class="card-text"><strong>Breed:</strong> <%= @post.breed.titleize %></p>
            <p class="card-text"><strong>Owner:</strong> <%= link_to @post.user.email, user_path(@post.user.id)  %></p>
            <p class="card-text"><strong>Price:</strong> <%= number_to_currency(@post.price, unit: "₱", separator: ".", delimiter: ",") %></p>
            <p class="card-text"><strong>Description:</strong> <%= @post.description %></p>
            <p class="card-text"><strong>Location:</strong> <%= @post.location %></p>
            <p class="card-text"><strong>Pick up/Meet up:</strong> <%= @post.pick_up == 'meet_up' ? 'Meet up' : 'Pick up' %></p>
        </div>
        <div class="post-delete">
            <%= link_to 'Delete', admin_user_post_path(@user, @post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger post-delete-btn' %>
        </div>
    </div> 
</div>