config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    authenticated :user do
      root to: 'posts#index', as: :authenticated_root
      resources :places
    end
  
    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :admin do
    resources :users do
      resources :posts, only: [ :index, :show, :destroy ]
    end
    # resources :posts, only: [ :show ]
  end
  
  resources :places

  resources :posts do
  	resources :comments
    resources :inquiries
    patch :report, on: :member
  end

  resources :users, only: [:index, :show, :update] do
    resources :reviews
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :inquiries, dependent: :destroy

  validates :pet_name, presence: true
  validates :category, presence: true
  validates :breed, presence: true
  validates :price, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :reported, inclusion: { in: [true, false] }

  mount_uploader :thumbnail, ThumbnailUploader
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
    before_action :set_user
    before_action :set_post, only: [ :show, :destroy]
    def index
        @posts = @user.posts
    end

    def show
    end

    def destroy
        if @post.destroy
            redirect_to admin_user_posts_path, notice: 'Post was successfully destroyed.'
        else
            render :show
        end
    end

    private
        def set_user
            @user = User.find(params[:user_id])
        end

        def set_post
            @post = @user.posts.find(params[:id])
        end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_if_admin
  before_action :set_post, only: [:show, :edit, :update, :destroy, :report]

  def index
    @posts = Post.where(availability: "available").order('created_at DESC')
  end

  def show
    @inquiry = @post.inquiries.find_by(inquirer_name: current_user.email)
  end

  def new
    @post = current_user.posts.build
  end

  def create 
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to post_url(@post), notice: 'Post create!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      # Handle successful update
      redirect_to @post, notice: 'Post updated.'
    else
      # Handle unsuccessful update
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post deleted.'
  end

  # Report post
  def report
    @post.update(reported: true)
    redirect_to post_path(@post), notice: 'Post reported'
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end


  def post_params
    params.require(:post).permit(:phone, :owner, :pet_name, :category, :breed, :price, :description, :pick_up, :location, :thumbnail, :availability, :advertisement)
  end

  
    def check_if_admin
      if current_user.admin?
        redirect_to '/admin/users'
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="card p-3 mb-5 mt-4" style="width: 50rem;">
  <%= form_with(model: @post, url: posts_path) do |form| %>

  <div class="row">
    <div class="mb-3 col">
        <%= form.label :owner, class: "form-label" %>
        <%= form.text_field :owner, class: "form-control" %>
    </div>
    <div class="mb-3 col">
        <%= form.label :pet_name, class: "form-label" %>
        <%= form.text_field :pet_name, class: "form-control" %>
    </div>
  </div>
    
   <div class="row">
      <div class="mb-3 col">
        <%= form.label :category, class: "form-label" %>
        <%= form.text_field :category, class: "form-control" %>
      </div>
      <div class="mb-3 col">
        <%= form.label :breed, class: "form-label" %>
        <%= form.text_field :breed, class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="mb-3 col">
        <%= form.label :price, class: "form-label" %>
        <%= form.number_field :price, step: :any, class: "form-control" %>
      </div>
      <div class="mb-3 col">
        <%= form.label :location, class: "form-label" %>
        <%= form.text_field :location, class: "form-control", id: "searchTextField" %>
      </div>
    </div>

    <div class="row">
      <div class="mb-3 col">
        <%= form.label :phone_number, class: "form-label" %>
        <%= form.text_field :phone, class: "form-control", id: "searchTextField" %>
    </div>
    <div class="mb-3 col">
        <%= form.label "Picture of your pet", class: "form-label" %>
        <%= form.file_field :thumbnail, class:"form-control"%>
      </div>
    </div>

    <div class="row">
    <div class="d-flex gap-2 mb-3 col">
      <%= form.radio_button :advertisement, 'For Adoption' %>
      <%= form.label :advertisement, 'For Adoption'%>
      <%= form.radio_button :advertisement, 'For Sale' %>
      <%= form.label :advertisement, 'For Sale'%>
    </div>


        <div class="d-flex gap-2 mb-3 col">
          <%= form.radio_button :pick_up, 'meet_up' %>
          <%= form.label :pick_up, 'Meet up'%>
          <%= form.radio_button :pick_up, 'pick_up' %>
          <%= form.label :pick_up, 'Pick up'%>
        </div>
  </div>

    <div class="mb-3">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_area :description, class: "form-control" %>
    </div>
      
      <%= form.submit 'Post pet', class: "btn btn-primary" %>
    <% end %>
</div>

app/views/posts/_navbar.html.erb
<nav class="navbar navbar-expand-lg " style="background-color: #86C8BC;">
  <div class="container-fluid me-3">
    <a href='/' class="navbar-brand text-light"><i class="fa-solid fa-dog" style="transform: scale(1.5); margin-left:15px;"></i></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <%# <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-light" role="button" data-bs-toggle="dropdown" aria-expanded="false" id="navbar-links">
            Links
          </a>
          <ul class="dropdown-menu">
            <li>
                asdf
            </li>
            <li>
                asdf
            </li>  %>
          </ul>
      </ul>
      <% if user_signed_in? %>
        <div style="display: flex; gap: 1.5rem;">

          <%= link_to places_path, class: "nav-item" do %>
          <i class="fa-solid fa-location-dot"></i>
        <% end %>

        <%= link_to user_path(current_user.id), class:"nav-item" do %>
          <i class="fa-solid fa-user"></i>
        <% end %>
 

        <%= link_to posts_path, class:"nav-item", id: "home-btn" do %>
          <i class="fa-solid fa-house-user"></i>
        <% end %>

        <%= link_to :back, class: "nav-item" do %>
          <i class="fa-solid fa-backward"></i>
        <% end %> 
        
        <%= link_to destroy_user_session_path, method: :delete, class: "nav-item " do%>
          <i class="fa-solid fa-xmark"></i>
        <% end %> 

      <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<div class="d-flex justify-content-center gap-2 mt-5">
  <div class="card post-card" style="width: 50rem; max-height: 600px;">
  <%= form_with(model: @post, url: post_path(@post), method: :patch) do |form| %>

  <div class="row">
    <div class="mb-3 col">
        <%= form.label :owner, class: "form-label" %>
        <%= form.text_field :owner, class: "form-control" %>
    </div>
    <div class="mb-3 col">
        <%= form.label :pet_name, class: "form-label" %>
        <%= form.text_field :pet_name, class: "form-control" %>
    </div>
  </div>
    
   <div class="row">
      <div class="mb-3 col">
        <%= form.label :category, class: "form-label" %>
        <%= form.text_field :category, class: "form-control" %>
      </div>
      <div class="mb-3 col">
        <%= form.label :breed, class: "form-label" %>
        <%= form.text_field :breed, class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="mb-3 col">
        <%= form.label :price, class: "form-label" %>
        <%= form.number_field :price, step: :any, class: "form-control" %>
      </div>
      <div class="mb-3 col">
        <%= form.label :location, class: "form-label" %>
        <%= form.text_field :location, class: "form-control", id: "searchTextField" %>
      </div>
    </div>

    <div class="row">
      <div class="mb-3 col">
        <%= form.label :phone_number, class: "form-label" %>
        <%= form.text_field :phone, class: "form-control", id: "searchTextField" %>
    </div>
    <div class="mb-3 col">
        <%= form.label "Picture of your pet", class: "form-label" %>
        <%= form.file_field :thumbnail, class:"form-control"%>
      </div>
    </div>

    <div class="row">
    <div class="d-flex gap-2 mb-3 col">
      <%= form.radio_button :advertisement, 'For Adoption' %>
      <%= form.label :advertisement, 'For Adoption'%>
      <%= form.radio_button :advertisement, 'For Sale' %>
      <%= form.label :advertisement, 'For Sale'%>
    </div>


        <div class="d-flex gap-2 mb-3 col">
          <%= form.radio_button :pick_up, 'meet_up' %>
          <%= form.label :pick_up, 'Meet up'%>
          <%= form.radio_button :pick_up, 'pick_up' %>
          <%= form.label :pick_up, 'Pick up'%>
        </div>
  </div>

    <div class="mb-3">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_area :description, class: "form-control" %>
    </div>
    <%= form.submit 'Post pet', class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

<script>
  function initialize() {
    var input = document.getElementById('searchTextField');
    new google.maps.places.Autocomplete(input);
  }

  google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/posts/index.html.erb
<div class="post-pet-container">
    <%= link_to new_post_path, class: "post-pet" do %>
        Post a pet
    <% end %>
</div>

<p class="pawsome-title"> Pawsome </p>

<div class="container" style="gap: 1.5rem;">
    <% @posts.each do |post| %>
        <div class="card" style="width: 15rem;">
            <div  class="card-img-top" >
                <%= image_tag post.thumbnail_url, class: "pet-thumbnail"%>
            </div>
            <div class="card-body">
                <div class="card-index">
                    <p class="card-title d-flex justify-content-center text-success"> <%= post.advertisement %>: <%= post.pet_name.titleize  %></p>
                    <p class="card-text"><i class="fa-solid fa-paw"></i> <%= post.category.titleize %>, <%= post.breed.titleize %></p>
                    <p class="card-text"><i class="fa-solid fa-user"></i> <%= post.owner %></p>
                    <p class="card-text"><i class="fa-solid fa-location-dot"></i> <%= post.location %></p> 
            </div>
                <%= link_to "Details", post_path(post), class: "btn btn-secondary btn-sm" %>
            </div>
        </div>
    <% end %>
</div>

app/views/posts/new.html.erb
<div class="container-fluid d-flex justify-content-center align-items-center flex-column">
<%= render 'posts/form' %>
</div>
<%# initialize and load google map autocomplete feature %>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
<script>
  function initialize() {
    var input = document.getElementById('searchTextField');
    new google.maps.places.Autocomplete(input);
  }

  google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/posts/show.html.erb
<div class="d-flex justify-content-center gap-2 mt-4" >
        <div class="card post-card" style="width: 30rem; max-height: 600px;">
            <div  class="card-img-top mb-2 mt-3" style="background-color: #86C8BC;">
                    <%= image_tag @post.thumbnail_url, class: "pet-thumbnail"%>
            </div> 
            <% if current_user.id == @post.user_id %> 
                <div>
                    <div class="show-post-tools">
                        <%= link_to post_inquiries_path(@post.id), class: "post-edit" do %>
                            <div id="inquiry-container">
                            <p> <i class="fa-regular fa-message"></i> </p> 
                            <p id="inquiry-count"> <%= @post.inquiries.count %> </p>
                            </div>
                        <% end %>
                        <%= link_to edit_post_url, class: "post-edit" do %>
                            <i class="fa-solid fa-pen-to-square"></i>
                        <% end %>
                    </div> 
                </div>
            <% else %>
                <%= link_to report_post_path(@post), method: :patch do %>
                    <i class="fa-solid fa-triangle-exclamation d-flex justify-content-end me-3 mt-3" style="color: black"></i>
                <% end %>
            <% end %>
            <div class="card-body">
                <div class="d-flex align-items-center gap-2">
                    <p style="color: green;"><strong><%= @post.advertisement %></strong></p> <p><%= @post.pet_name.titleize  %></p>
                </div>
                <p class="card-text"><strong>Category:</strong> <%= @post.category.titleize %></p>
                <p class="card-text"><strong>Breed:</strong> <%= @post.breed.titleize %></p>
                <p class="card-text"><strong>Owner:</strong> <%= link_to @post.user.email, user_path(@post.user.id)  %></p>
                <p class="card-text"><strong>Phone number: </strong> <%= @post.phone %></p>
                <p class="card-text"><strong>Price:</strong> <%= number_to_currency(@post.price, unit: "₱", separator: ".", delimiter: ",") %></p>
                <p class="card-text"><strong>Description:</strong> <%= @post.description %></p>
                <p class="card-text"><strong>Location:</strong> <%= @post.location %></p>
                <p class="card-text"><strong>Pick up/Meet up:</strong> <%= @post.pick_up == 'meet_up' ? 'Meet up' : 'Pick up' %></p>
                <%= render 'inquiries/form' %>
            </div>
        </div> 

        <div class="card post-card" style="width: 30rem; height: 600px; max-height: 400px overflow: hidden;" id="comment-container">
            <%= render 'comments/form' %>
            <p class="m-1"><%= @post.comments.count %> comments</p>
            <%= render @post.comments %>
        </div>
</div>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>