config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    authenticated :user do
      root to: 'posts#index', as: :authenticated_root
      resources :places
    end
  
    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :admin do
    resources :users do
      resources :posts, only: [ :index, :show, :destroy ]
    end
    # resources :posts, only: [ :show ]
  end
  
  resources :places

  resources :posts do
  	resources :comments
    resources :inquiries
    patch :report, on: :member
  end

  resources :users, only: [:index, :show, :update] do
    resources :reviews
  end
end

app/models/user.rb
class User < ApplicationRecord
# Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :reviews
  has_many :transactions

  # after_create :send_welcome_email

  # def send_welcome_email
  #   UserMailer.welcome(self).deliver_now
  # end

  mount_uploader :avatar, AvatarUploader
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.where(admin: false || nil)
  end

  # GET /users/1 or /users/1.json
  def show
    @posts = @user.posts
  end

  # GET /users/new
  # def new
  #   @user = User.new
  # end

  # POST /users or /users.json
  # def create
  #   @user = User.new(user_params)
  #   # @user.skip_confirmation!


  #   respond_to do |format|
  #     if @user.save
  #       # AdminConfirmationMailer.signed_up(@user).deliver_now
          # redirect_to admin_user_url(@user)
  #     else
          # render :new
  #     end
  #   end
  # end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        redirect_to admin_user_path(@user), notice: "Account successfully updated"
      else
        render :edit
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.posts.destroy_all
    @user.destroy
    redirect_to admin_users_path
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password)
    end

    def check_if_admin
      redirect_to authenticated_root_path unless current_user.admin?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
        @user = User.find(params[:id])
    end
    
    def show
        @user = User.find(params[:id])
        @posts = Post.where(user_id: params[:id])
        @connections = Connection.where(user_id: params[:id])
    end 

    def update
        @user = User.find(params[:id]) 
        
        if @user.update(user_params)
            redirect_to user_path(params[:id])
        end
    end

    private
    def user_params
      params.require(:user).permit(:avatar)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin, user], local: true) do |form| %>
  <div class="form-group">
    <%= form.text_field :email, class: "form-control", placeholder: "Email" %>
  </div>

  <div class="form-group">
    <%= form.password_field :password, autocomplete: "new-password", placeholder: "Password", class: "form-control" %>
      <% if @minimum_password_length %>
    <em class="form-text text-muted">(Password must be <%= @minimum_password_length %> characters minimum)</em>
    <% end %>
  </div>

  <div class="actions d-flex justify-content-center">
    <%= form.submit 'Add User', class: "btn btn-primary" %>
  </div>
  
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<div class="d-flex flex-column dashboard">

  <h1 class="mb-2">Admin Access: <%= current_user.email %></h1>

  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Users</th>
        <th scope="col">Posts</th>
        <th scope="col">Reports</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.email, admin_user_path(user) %></td>
          <td><%= link_to user.posts.size, admin_user_posts_path(user) %></td>
          <td><%= user.posts.where(reported: true).count %></td>
        </tr>
      <% end %>

    </tbody>
  </table>
</div>

app/views/admin/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="d-flex justify-content-center mt-3">
    <div class="d-flex justify-content-center align-items-center form">
        <div>
            <h1 class="form-header">Add New User</h1>
            <%= render 'form', user: @user %>
        </div>
    </div>
</div>

app/views/admin/users/pending_signup.html.erb
<div class="d-flex flex-column dashboard">
    <h1 class="mb-2">Pending Users</h1>
    <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Email</th>
        <th scope="col">Action</th>
      </tr>
    </thead>

    <tbody>
      <% @pending_users.each do |user| %>
        <tr>
            <td class="mb-1 d-flex" style="color: var(--primary)"><%= user.email %></td>
            <% # Update user attribute confirmation_at: DateTime.current %>
            <td><%= link_to 'Confirm', admin_path(user), method: :patch, style: 'color: green' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/users/show.html.erb
<div class='container-xl mb-2'>
  <div class="row">
    <div class="col-4  text-center">
      <div class="card d-flex justify-content-center align-items-center">
        <%= render 'users/partials/profile' %>
      </div>
    </div>
    <div class="col-8">
      <div class="row mb-3">
        <div class="card">
        <%= render 'users/partials/posts' %>
        </div>
      </div>
      <div class="row">
        <div class="card">
          <% if @user.reviews.size > 0 %>
            <% @user.reviews.each do |review| %>
                <div class="row border-bottom my-3">
                  <div class="col-1">
                    <%= image_tag User.find_by(email: review.reviewer).avatar_url || 'default_profile', class: 'rounded-circle', style: 'width: 50px; height: 50px;' %>        
                  </div>
                  <div class="col-11">
                    <div class="row"><%= review.reviewer %></div>
                    <div class="row"><%= review.rating %> &#11088; rating</div>
                    <div class="row my-2"><%= review.comment %></div>
                  </div>
                </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <h1><%= link_to "Delete User", admin_user_path(@user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'  %></h1>
</div>