config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    authenticated :user do
      root to: 'posts#index', as: :authenticated_root
      resources :places
    end
  
    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :admin do
    resources :users do
      resources :posts, only: [ :index, :show, :destroy ]
    end
    # resources :posts, only: [ :show ]
  end
  
  resources :places

  resources :posts do
  	resources :comments
    resources :inquiries
    patch :report, on: :member
  end

  resources :users, only: [:index, :show, :update] do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :comment, presence: true
end

app/models/connection.rb
class Connection < ApplicationRecord
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  belongs_to :post

  validates :inquirer_name, presence: true
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :inquiries, dependent: :destroy

  validates :pet_name, presence: true
  validates :category, presence: true
  validates :breed, presence: true
  validates :price, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :reported, inclusion: { in: [true, false] }

  mount_uploader :thumbnail, ThumbnailUploader
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
# Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :reviews
  has_many :transactions

  # after_create :send_welcome_email

  # def send_welcome_email
  #   UserMailer.welcome(self).deliver_now
  # end

  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
		@post = Post.find(params[:post_id])
	 	@comment = @post.comments.create(params[:comment].permit(:name, :comment))
		redirect_to post_path(@post)	
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  before_action :verify_user, only: [:index]

  def index
    @post = Post.find(params[:post_id])
    @inquiries = @post.inquiries
  end

  def create
		@post = Post.find(params[:post_id])
	 	@inquiry = @post.inquiries.create(params[:inquiry].permit(:inquirer_name))
		redirect_to post_path(@post)	
	end

	def destroy
		@post = Post.find(params[:post_id])
		@inquiry = @post.inquiries.find(params[:id])
		@inquiry.destroy
		redirect_to post_path(@post)
	end

  def verify_user
    redirect_to authenticated_root_path, notice: "You do not have access to that post" unless Post.find(params[:post_id]).user_id == current_user.id
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: %i[ show edit update destroy ]

  # GET /places or /places.json
  def index
    @places = Place.all
  end

  # GET /places/1 or /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places or /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to place_url(@place), notice: "Place was successfully created." }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1 or /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to place_url(@place), notice: "Place was successfully updated." }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1 or /places/1.json
  def destroy
    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url, notice: "Place was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:name, :latitude, :longitude)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_if_admin
  before_action :set_post, only: [:show, :edit, :update, :destroy, :report]

  def index
    @posts = Post.where(availability: "available").order('created_at DESC')
  end

  def show
    @inquiry = @post.inquiries.find_by(inquirer_name: current_user.email)
  end

  def new
    @post = current_user.posts.build
  end

  def create 
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to post_url(@post), notice: 'Post create!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      # Handle successful update
      redirect_to @post, notice: 'Post updated.'
    else
      # Handle unsuccessful update
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post deleted.'
  end

  # Report post
  def report
    @post.update(reported: true)
    redirect_to post_path(@post), notice: 'Post reported'
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end


  def post_params
    params.require(:post).permit(:phone, :owner, :pet_name, :category, :breed, :price, :description, :pick_up, :location, :thumbnail, :availability, :advertisement)
  end

  
    def check_if_admin
      if current_user.admin?
        redirect_to '/admin/users'
      end
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def create
        @user = User.find(params[:user_id])
        @review = @user.reviews.build(review_params)
        @review.reviewer = current_user.email
        if @review.save 
            redirect_to user_path(params[:user_id])
        end
      end
    
      private
        def review_params
          params.require(:review).permit(:rating, :comment)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
        @user = User.find(params[:id])
    end
    
    def show
        @user = User.find(params[:id])
        @posts = Post.where(user_id: params[:id])
        @connections = Connection.where(user_id: params[:id])
    end 

    def update
        @user = User.find(params[:id]) 
        
        if @user.update(user_params)
            redirect_to user_path(params[:id])
        end
    end

    private
    def user_params
      params.require(:user).permit(:avatar)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<section style="">
    <div class="comment-box ml-1">
      <p style="margin: 5px" >
      <%= comment.name %>
      <%= comment.comment %>
      </p>  

      <% if current_user.email == comment.name %>
      <%= link_to [comment.post, comment],
                method: :delete, class: "delete-comment", data: { confirm: 'Are you sure?' } do %>
                <p style="margin: 5px">
                    <i class="fa-solid fa-trash"></i>
                </p>
      <% end %>
    <% end %>
    </div>
</section>

app/views/comments/_form.html.erb
<div class="card p-3">
  <%= form_with(model: [@post, @post.comments.new], local: true) do |form| %>
    <%= form.hidden_field :name, :value => current_user.email %>
    <div class="mb-3">
      <%= form.label :comment, class: "form-label"%>
      <%= form.text_area :comment, class: "form-control" %>
    </div>
    <%= form.submit 'Comment', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/inquiries/_form.html.erb
<div class=" p-1">
  <%= form_with(model: [@post, @post.inquiries.new], local: true) do |form| %>
    <%= form.hidden_field :inquirer_name, :value => current_user.email %>

    <% if current_user.id != @post.user_id %>
      <% if @post.availability != 'available' %>
          <%= button_tag "#{@post.advertisement == 'For Sale' ? 'Sold' : 'Adopted'}", type: 'button', class: "btn btn-secondary", disabled: true %>
      <% elsif @inquiry == nil %>
        <%= form.submit 'Inquire', class: "btn btn-primary" %>
      <% elsif @inquiry.inquirer_name == current_user.email%>
          <%= button_tag 'Inquired', type: 'button', class: "btn btn-secondary", disabled: true %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/inquiries/_inquiry.html.erb
<div class="comment-box ml-1">
      <p style="margin: 5px">
      <%= comment.name %>
      <%= comment.comment %>
      </p>

      <% if current_user.email == comment.name %>
      <%= link_to [comment.post, comment],
                method: :delete, class: "delete-comment", data: { confirm: 'Are you sure?' } do %>
                <p style="margin: 5px">
                    <i class="fa-solid fa-trash"></i>
                </p>
      <% end %>
    <% end %>
</div>

app/views/inquiries/copyindex.html.erb
<p>Inquiries for <%= @post.pet_name %></p>

<div id="inquiry-details">
    <div id="inquiry-content">
<% @inquiries.each do |inquiry| %>
    <p>Inquirer email: <%= inquiry.inquirer_name %></p>
    <% if @post.availability != 'available' %>
        <%= form_with(model: @post, method: :patch) do |form|%>
            <%= form.hidden_field :availability, value: "available" %>
            <%= form.submit "Available" %> 
        <% end %>
    <% else %>
        <%= form_with(model: @post, method: :patch) do |form|%>
            <%= form.hidden_field :availability, value: "#{@post.advertisement == 'For Sale' ? 'Sold' : 'Adopted'}" %>
            <%= form.hidden_field :update, value: "#{@post.advertisement == 'For Sale' ? 'Sold' : 'Adopted'}" %>
            <%= form.submit "#{@post.advertisement == 'For Sale' ? 'Sold' : 'Adopted'}" %>
        <% end %>
    <% end %>
<% end %>
<%= console %>
</div>
</div>

app/views/inquiries/index.html.erb
<p id="pet-inquiry"><%= @post.pet_name %></p>
<div class="d-flex justify-content-center">
<div class="card" style="width: 12rem;">
    <%= image_tag @post.thumbnail_url, class: "pet-thumbnail"%>
</div>
</div>

<div class="container my-1 d-flex justify-content-center">
  <div class="row">
    <table class="table table-bordered text-center" style="width: 700px">
    <thead>
        <tr style="background-color: #86C8BC;">
            <th scope="col">Inquirer email</th>
            <th scope="col">Status </th>
        </tr>
    </thead>
    <tbody>
            <% if @inquiries.count > 0 %>
            <% @inquiries.each do |inquiry| %>
            <tr>    
                <td> <%= inquiry.inquirer_name %> </td>
                <td>
                    <% if @post.availability != 'available' %>
                        <%= form_with(model: @post, method: :patch) do |form|%>
                        <%= form.hidden_field :availability, value: "available" %>
                        <%= form.submit "Available" %>
                    <% end %>
                    <% else %>
                        <%= form_with(model: @post, method: :patch) do |form|%>
                        <%= form.hidden_field :availability, value: "#{@post.advertisement == 'For Sale' ? 'Sold' : 'Adopted'}" %>
                        <%= form.hidden_field :update, value: "#{@post.advertisement == 'For Sale' ? 'Sold' : 'Adopted'}" %>
                        <%= form.submit "#{@post.advertisement == 'For Sale' ? 'Sold' : 'Adopted'}" %>
                    <% end %>
                    <% end %> 
                </td>
            </tr>
            <% end %>
            <% else %>
                <tr>
                    <td colspan="6">
                        <p class="m-1">No inquiry yet.</p>
                    </td>
                </tr>
            <% end %>
            <tbody>
        </table>
    </div>
</div>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<div style="margin-top: 2.5rem">
<%= form_with model: @place, local: true, data: {
  controller: :maps,
  action: "google-maps-callback@window->maps#initializeMap"
} do |form| %>

<div class="map-container">

<div class="field">
  <%= form.search_field :search, name: nil, class: 'form-control', data: { target: "maps.field", action: "keydown->maps#preventSubmit" }, class: "search-location-bar", id: "search-bar" %>
</div>

<div class="field-coordinates">
  <%= form.label :latitude %>
  <%= form.text_field :latitude, class: 'form-control', data: { target: "maps.latitude" }, class: "field-coordinates", id: "coordinates" %>
</div>

<div class="field-coordinates">
  <%= form.label :longitude %>
  <%= form.text_field :longitude, class: 'form-control', data: { target: "maps.longitude" } %>
</div>


  <%= content_tag :div, nil, data: { target: "maps.map" }, class: "map" %>
<% end %> 
</div>
</div>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @place.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @place.longitude %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

# views/places/show.html.erb
<%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=15&size=400x300&center=#{@place.latitude},#{@place.longitude}&key=#{Rails.application.credentials.google_maps_api_key}", alt: "Map" %>